# Generated by Django 5.2.7 on 2025-11-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('men', 'Мужские'), ('women', 'Женские'), ('unisex', 'Унисекс')], default='unisex', max_length=10, verbose_name='Пол'),
        ),
    ]
