# Generated by Django 5.2.7 on 2026-01-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
